apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    name: db-deployment
    app: voting-application
spec:
  replicas: 2
  selector:
     matchLabels:
       app: voting-application
  template:
    metadata:
      name: db-deployment
      labels:
        name: db-deployment
        app: voting-application
    spec:
      containers:
        - name: db-deployment
          image: postgres:9.4
          env:
           - name: POSTGRES_USER
             value: "postgres"
           - name: POSTGRES_PASSWORD
             value: "postgres"
           - name: POSTGRES_HOST_AUTH_METHOD
             value: trust
          ports:
           - containerPort: 5432
          volumeMounts:
           - mountPath: /var/lib/postgresql/data
             name: db-data
      volumes:
       - name: db-data
         emptyDir: {}   
