apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: voting-application
spec: 
  replicas: 2
  selector:
    matchLabels: 
      name: redis-deployment
      app: voting-application
  template:
    metadata:
      name: redis-deployment
      labels:
        name: redis-deployment
        app: voting-application
    spec:
      containers:
      - name: redis-deployment
        image: redis:alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}    


