apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: voting-application
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-deployment
    app: voting-application    
