apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-deployment
    app: voting-application
spec: 
  replicas: 2
  selector:
    matchLabels: 
      name: result-deployment
      app: voting-application
  template:
    metadata:
      name: result-deployment
      labels:
        name: result-deployment
        app: voting-application
    spec:
      containers:
      - name: result-deployment
        image: kodekloud/examplevotingapp_result:before
        ports:
        - containerPort: 80    

