apiVersion: v1
kind: Service
metadata :
  name: result-service
spec: 
  type: NodePort
  selector:
    name: result-deployment
    app: voting-application
  ports:
    - port: 5001
      targetPort : 80
      nodePort : 31001
          

