apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    name: vote-deployment
    app: voting-application
spec: 
  replicas: 2
  selector:
    matchLabels: 
      name: vote-deployment
      app: voting-application
  template:
    metadata:
      name: vote-deployment
      labels:
        name: vote-deployment
        app: voting-application
    spec:
      containers:
      - name: vote-deployment
        image: kodekloud/examplevotingapp_vote:before
        ports:
        - containerPort: 80    
