apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    name: worker
    app: voting-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
      label: voting-application
  template:
    metadata:
      name: worker
      labels:
        name: worker
        label: voting-application
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker    
